stages:
  - dep
  - build
  - test
  - release

variables:
  BUILD_BASE: rust:1 # rust:1-alpine3.14

dep:
  image: $BUILD_BASE
  stage: dep
  script:
    - mkdir -p .cargo
    - export CARGO_HOME=$(pwd)/.cargo
    - cargo install --path .
  cache:
    - &cache_settings
      paths:
      - .cargo
      - target/debug
      # - target/release
      key: &cache_key
        files:
        - Cargo.lock
      policy: pull-push

build:latest:
  image: $BUILD_BASE
  stage: build
  tags:
    - docker
  script:
    - mkdir -p .cargo
    - export CARGO_HOME=$(pwd)/.cargo
    - cargo build
  only:
    - master
  cache:
    - <<: *cache_settings
      policy: pull
  artifacts:
    paths:
    - target/debug/nbd-rs
    expire_in: 1 month

build:release:
  image: $BUILD_BASE
  stage: release
  tags:
    - docker
  script:
    - mkdir -p .cargo
    - export CARGO_HOME=$(pwd)/.cargo
    - cargo build --release
  only:
    - tags
  artifacts:
    paths:
    - target/release/nbd-rs
    expire_in: never

build:dev:
  image: $BUILD_BASE
  stage: build
  tags:
    - docker
  script:
    - mkdir -p .cargo
    - export CARGO_HOME=$(pwd)/.cargo
    - cargo build
  except:
    - master
  cache:
    - <<: *cache_settings
      policy: pull
  artifacts:
    paths:
    - target/debug/nbd-rs
    expire_in: 2 days

test:unit:
  image: $BUILD_BASE
  stage: test
  before_script:
    - fallocate -l 64M alpine # dummy image file
  script:
    - mkdir -p .cargo
    - export CARGO_HOME=$(pwd)/.cargo
    - cargo test -- --test-threads 1
  after_script:
    - rm alpine
  cache:
    - <<: *cache_settings
      policy: pull
