[package]
name = "nbd-proxy-rs"
version = "0.1.0"
authors = ["Furkan Mustafa <furkan@rainlab.co.jp>", "Bilal Ozdemir <bilal@rlab.io>"]
edition = "2018"

[dependencies]
libc = "0.2"
mmap-safe = "0.0.2"
clap = "2.33"
url = "2.2"
#byteorder = "1.3.4"
