version: '3.5'
services:
  nbd_server:
    build: .
    ports:
    - 10809:10809
    command: [ "--export", "disk1", "sharded", "s3:http://miniotest:miniotest@minio:9000/disks/mydisk1" ]
    environment:
      RUST_LOG: info,nbd_rs=debug
      RUST_BACKTRACE: "1"

  # devshell:
  #   # scale: 0
  #   build:
  #     context: .
  #     target: builder
  #   command: sleep infinity

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 38827:38827
    command: [ "server", "--console-address", ":38827", "/data" ]
    volumes:
      - ./minio-data:/data
    environment:
      - MINIO_ROOT_USER=miniotest
      - MINIO_ROOT_PASSWORD=miniotest

  # test:
  #   depends:
  #     - nbd
  #   image: dkr.rlab.io/system/dockerized/qemu:latest
  #   command:
  #     - /bin/sh
  #     - -c
  #     - |
  #       # kill after 10 seconds
  #       timeout -s 9 10 \
  #       qemu-img info nbd:nbd_server:10891
